- name: Hello World Sample
  hosts: all
  tasks:
    - name: Hello Message
      debug:
        msg: "Hello Test World!"
    - name: Pause for 5 minutes to build app cache
      ansible.builtin.pause:
        minutes: 3
    - name: extra vars
      debug:
        msg: "{{ ext_env | default('not set') }}"
